use_frameworks!

platform :ios, '9.0'

target 'LDZFCGContextObject_Example' do
  pod 'LDZFCGContextObject', :path => '../'

  target 'LDZFCGContextObject_Tests' do
    inherit! :search_paths

    
  end
end
